###############################################################################
# TELEGRAF CONFIGURATION FOR LATHE MONITORING
###############################################################################

[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "5s"

###############################################################################
# MQTT FLOAT INPUT
###############################################################################

[[inputs.mqtt_consumer]]

  servers = ["tcp://mosquitto:1883"]

  topics = [
    "factory/+/temperature/#",
    "factory/+/speed/#",
    "factory/+/current/#"
  ]

  username = "bmetk"
  password = "iot26"

  qos = 0
  connection_timeout = "20s"

  data_format = "value"
  data_type = "float"

  name_override = "lathe_raw"

###############################################################################
# TOPIC FLOAT PARSING
###############################################################################

  [[inputs.mqtt_consumer.topic_parsing]]

    topic = "factory/+/+/+/+"

    tags = "_/machine/aspect/sensor/metric"

###############################################################################
# MQTT STRING INPUT
###############################################################################

[[inputs.mqtt_consumer]]

  servers = ["tcp://mosquitto:1883"]

  topics = [
    "factory/+/vibration/#"
  ]

  username = "bmetk"
  password = "iot26"

  data_format = "value"
  data_type = "string"

  name_override = "lathe_vibration_raw"

###############################################################################
# TOPIC STRING PARSING
###############################################################################

   [[inputs.mqtt_consumer.topic_parsing]]

    topic = "factory/+/+/+/+"

    tags = "_/machine/aspect/sensor/metric"

###############################################################################
# OUTPUT
###############################################################################

[[outputs.influxdb_v2]]

  urls = ["http://influxdb:8086"]

  token = "HH7I4j8dZE8hOxVIsVPq5XTHe9LXEqfiPYq8xtSCe3wpSyEv4TeZSns3eUD5-No8twMD7E45y4-1bRD7z_1JwQ=="

  organization = "bmetk"

  bucket = "openmaps"